CREATE TABLE TABLA1(
ID INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(20)
)

INSERT INTO TABLA1 VALUES(1,'LUIS');
INSERT INTO TABLA1 VALUES(2,'MARCO');
INSERT INTO TABLA1 VALUES(3,'PEDRO');

CREATE TABLE TABLA_COPY(
ID INT ,
NOMBRE VARCHAR(20)
)

SELECT* FROM TABLA1
SELECT* FROM TABLA_COPY
DELETE FROM TABLA_COPY
ALtER TABLE TABLA_COPY ADD  NOMBRE1 VARCHAR(20);

CREATE TRIGGER TRIG ON TABLA1 
AFTER UPDATE 
AS
BEGIN

DECLARE @NOMBRE AS VARCHAR(20),
		@ID AS INT,
		@VAL AS VARCHAR(20)
DECLARE CURSOR1 CURSOR FOR
SELECT ID,NOMBRE FROM TABLA1
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @ID, @NOMBRE
WHILE @@FETCH_STATUS = 0
BEGIN
INSERT INTO TABLA_COPY VALUES(@ID,@NOMBRE)
SELECT @VAL= CONVERT(VARCHAR(20),@ID,112)
--PRINT @VAL+','+@NOMBRE
FETCH NEXT FROM CURSOR1 INTO @ID, @NOMBRE
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
END

SELECT* FROM TABLA1
SELECT* FROM TABLA_COPY
DELETE FROM TABLA_COPY
UPDATE TABLA1 SET NOMBRE='JORGE'